import { Controller, Get, UseGuards } from '@nestjs/common';
import { Property } from '@work-os-demo/types';
import { AuthGuard } from '../auth';

const properties: Property[] = [
  {
    id: '1',
    address: '24 Maple Street, Manchester, M1 2AB',
    type: '2-bed Flat',
    bedrooms: 2,
    monthlyRent: 1200,
    tenant: 'John Smith',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-12-15'),
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '2',
    address: '15 Oak Avenue, Birmingham, B2 4QA',
    type: '3-bed House',
    bedrooms: 3,
    monthlyRent: 1500,
    tenant: 'Sarah Johnson',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-11-20'),
    complianceStatus: 'expiring-soon',
    arrears: 1500,
  },
  {
    id: '3',
    address: '8 Park Lane, Leeds, LS1 5JG',
    type: '1-bed Studio',
    bedrooms: 1,
    monthlyRent: 850,
    tenant: null,
    tenancyStatus: 'vacant',
    nextInspection: null,
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '4',
    address: '42 High Street, Liverpool, L1 9DQ',
    type: '2-bed Flat',
    bedrooms: 2,
    monthlyRent: 1100,
    tenant: 'Michael Brown',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-12-01'),
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '5',
    address: '67 Victoria Road, Sheffield, S1 2GH',
    type: '4-bed House',
    bedrooms: 4,
    monthlyRent: 1800,
    tenant: 'Emma Wilson',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2025-01-10'),
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '6',
    address: '33 Church Street, Bristol, BS1 5PF',
    type: '2-bed Flat',
    bedrooms: 2,
    monthlyRent: 1250,
    tenant: 'David Taylor',
    tenancyStatus: 'notice',
    nextInspection: new Date('2024-11-25'),
    complianceStatus: 'compliant',
    arrears: 850,
  },
  {
    id: '7',
    address: '91 Station Road, Newcastle, NE1 4ST',
    type: '3-bed House',
    bedrooms: 3,
    monthlyRent: 1400,
    tenant: 'Lisa Anderson',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-12-20'),
    complianceStatus: 'expired',
    arrears: 0,
  },
  {
    id: '8',
    address: '12 Mill Lane, Nottingham, NG1 3AA',
    type: '1-bed Flat',
    bedrooms: 1,
    monthlyRent: 900,
    tenant: null,
    tenancyStatus: 'vacant',
    nextInspection: null,
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '9',
    address: '56 Bridge Road, Leicester, LE1 6ZH',
    type: '2-bed Flat',
    bedrooms: 2,
    monthlyRent: 1150,
    tenant: 'James Martin',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-11-30'),
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '10',
    address: '78 Green Lane, Southampton, SO14 0AA',
    type: '3-bed House',
    bedrooms: 3,
    monthlyRent: 1600,
    tenant: 'Rachel White',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-12-05'),
    complianceStatus: 'expiring-soon',
    arrears: 0,
  },
  {
    id: '11',
    address: '29 Castle Street, Edinburgh, EH1 2DP',
    type: '2-bed Flat',
    bedrooms: 2,
    monthlyRent: 1300,
    tenant: 'Tom Harris',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2025-01-15'),
    complianceStatus: 'compliant',
    arrears: 0,
  },
  {
    id: '12',
    address: '45 Market Square, Cardiff, CF10 1BH',
    type: '3-bed House',
    bedrooms: 3,
    monthlyRent: 1450,
    tenant: 'Sophie Clark',
    tenancyStatus: 'occupied',
    nextInspection: new Date('2024-12-10'),
    complianceStatus: 'expiring-soon',
    arrears: 0,
  },
] as const;

@Controller('properties')
export class PropertiesController {
  @Get('properties')
  @UseGuards(AuthGuard)
  getProperties() {
    return properties;
  }
}
